import requests
import time
from config import PLACES_API_KEY
import pandas as pd

API_KEY = PLACES_API_KEY
NEARBY_SEARCH_URL = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
PLACE_DETAILS_URL = 'https://maps.googleapis.com/maps/api/place/details/json'

# Get nearby hotels within a radius.
def get_nearby_places(location, radius, api_key):
    hotels = []
    seen_place_ids = set()  # A set to track unique place_ids
    params = {
        'location': location,
        'radius': radius,
        'type': 'lodging|hotel',
        'key': api_key
    }
    
    '''
    Google allows up to 20 results per page, up to 3 pages.
    I implement 'page' here to get as much data as I can.
    https://developers.google.com/maps/documentation/places/web-service/search-nearby#pagetoken
    '''
    page = 1  
    while True:
        response = requests.get(NEARBY_SEARCH_URL, params=params)
        data = response.json()

        # Saving results and checking for duplicates.
        for place in data.get('results', []):
            place_id = place['place_id']
            if place_id not in seen_place_ids:
                hotels.append(place)
                seen_place_ids.add(place_id)

        next_page_token = data.get('next_page_token')
        if not next_page_token:
            break
        params['pagetoken'] = next_page_token
        page += 1
        time.sleep(2)
    return hotels

# Get reviews for a given place_id
def get_place_reviews(place_id, api_key):
    params = {
        'place_id': place_id,
        'key': api_key
    }
    response = requests.get(PLACE_DETAILS_URL, params=params)
    reviews = response.json().get('result', {}).get('reviews', [])
    return reviews


def main():
    '''
    nearby_coordinates variable loads a set of coordinates generated by 'generate_coords.py' script.
    We will fetch hotel data for each coordinate and remove duplicates.
    '''
    nearby_coordinates = pd.read_csv('datasets/grid_coordinates.csv')

    places_data = []
    reviews_data = []
    # For each location, get the hotels in 1km radius.
    for loc in nearby_coordinates.values:
        places = get_nearby_places(f"{loc[0]},{loc[1]}", 1000, API_KEY)

        for place in places:
            place_id = place['place_id']
            place_name = place.get('name')
            rating = place.get('rating')
            address = place.get('vicinity')

            # Collect the data in a format read-able by pandas for later csv generation.
            places_data.append({
                'place_id': place_id,
                'name': place_name,
                'rating': rating,
                'address': address
            })

            # For each fetched hotel, get its reviews (up to 5 limit by Google Places API).
            reviews = get_place_reviews(place_id, API_KEY)
            for review in reviews:
                print(f"\rRetrieved {len(reviews_data)} reviews.", end='')
                reviews_data.append({
                    'place_id': place_id,
                    'author_name': review.get('author_name'),
                    'rating': review.get('rating'),
                    'text': review.get('text'),
                    'time': review.get('relative_time_description')
                })

    # Export data to csv.
    pd.DataFrame(places_data).to_csv('datasets/hotels_athens.csv', index=False)
    pd.DataFrame(reviews_data).to_csv('datasets/reviews_athens.csv', index=False)
    print("Data saved to 'datasets' folder.")

if __name__ == '__main__':
    main()
    